apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: jellyfin-config
  storageClassName: local-storage


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
      namespace: jellyfin
      name: jellyfin-config
  hostPath:
    path: "<hostpath>"