---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <size>
  volumeName: jellyfin-data
  storageClassName: local-storage  

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-data
spec:
  capacity:
    storage: <size>
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
      namespace: jellyfin
      name: jellyfin-data
  hostPath:
    path: "<hostpath>"