apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jellyfin.kube.eu.aperturect.com`)
      priority: 10
      services:
        - name: jellyfin
          port: 8096
  tls:
    certResolver: default
